/*
    Intended for testing purpose
*/

-- Table Order 
-- DROP table public.orders

create table public.orders (
    id bigint generated by default as identity not null primary key,
    user_id uuid references auth.users,
    order_number text null,
    state text null,
    amount text null,
    delivery_date text null,
    created_at text null
  );

-- Replace user_id by the registered on ur supabase instance
INSERT INTO "orders" (id, user_id, order_number, state, amount, delivery_date, created_at ) 
VALUES ('100', '','34523','Delivered','132.987','7 February 2023', '7 June 2022'),
('101', '','45123','Delivered','256.987','27 March 2023', '16 December 2023'),
('102', '','52343','Packaging','190.000','11 March 2023', '3 September 2022'),
('103', '','78678','Delivered','1.783.987','7 February 2023', '20 January 2023'),
('104', '','89089','Recieved','783.234','9 April 2023', '15 February 2023');


-- Table order_details
create table public.order_detail (
    id bigint generated by default as identity not null primary key,
    order_id bigint references public.orders,
    product_items jsonb null,
    shipping_address text null,
    mobile_number text null,
    created_at text
  );

INSERT INTO "order_detail" (id, order_id, product_items, shipping_address, mobile_number) 
VALUES ('11', '101', '[{"product_id":"1000", "qty":"3"}, {"product_id":"1001", "qty":"2"}]', 'Celeste Slater 606-3727 Ullamcorper. Roseville NH 11523', '(786) 713-8616');




-- Orders, dont forget to replace user_id
INSERT INTO "orders" (id, user_id, order_number, state, amount, delivery_date, created_at ) 
VALUES ('100', '','34523','Delivered','132.987','7 February 2023', '7 June 2022'),
('101', '','45123','Delivered','256.987','27 March 2023', '16 December 2023'),
('102', '','52343','Packaging','190.000','11 March 2023', '3 September 2022'),
('103', '','78678','Delivered','1.783.987','7 February 2023', '20 January 2023'),
('104', '','89089','Recieved','783.234','9 April 2023', '15 February 2023');

-- Order detail
INSERT INTO "order_detail" (id, order_id, product_items, shipping_address, mobile_number) 
VALUES ('11', '101', '[{"product_id":"1000", "qty":"3"}, {"product_id":"1001", "qty":"2"}]', 'Celeste Slater 606-3727 Ullamcorper. Roseville NH 11523', '(786) 713-8616');